### ISSUE TITLE
Add Additional Instructions to README

### ISSUE THREAD

**Issue by nclairesays** [orange-cloudfoundry/matomo-cf-service#1]
Thanks for all of this! Followed your instructions but did find some action items missing from readme. We had to add/do the following to get it to run app and pass tests:

- Had to figure out how to build a jar file and referred to the [Official Maven Docs](https://docs.spring.io/spring-boot/docs/current/reference/html/getting-started.html#getting-started-first-application-executable-jar)
and added the following code to pom.xml
```
<build>
    <plugins>
        <plugin>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-maven-plugin</artifactId>
        </plugin>
    </plugins>
</build>
```
- Saved pom.xml and run `mvn package`  so that the package generated in target/matomo-cf-service-0.7.0.jar as specified in the mymanifest
- _Then_ `cf push -f mymanifest.yml`

We also had a couple issues related to the matomo release version.  Had to do the following to get it to run: 
- TestMatomoReleases.java --> testReleaseList
Removed `Assertions.assertEquals(1, rellist.size(), "Size of release list should be 1");` Maybe i'm misunderstanding how the test works but it was a little confusing because your documentation says we can have more than one release number? And our release list size was more than 1
- In Parameters.java, changed the version variable value
- In application.yml, changed test:currentRelease number 

Might be helpful to update readme so people know they might need update these files too.

**Comment by pdechamboux** [comment]
Thanks Claire for your contribution.
Relevant corrections should have been provided with the lastest commits.
